name: Delete Object Files

on:
  push:
    paths:
      - '**.o'

jobs:
  clean_up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find and delete object files
        run: |
          find . -type f -name "*.o" -exec rm -f {} +
